title: "Hanqi Wang"
author:
  name: "Hanqi Wang"
  email: "hanqiwang24@example.com"
  github: "hanqiwang24"
description: "PhD student | Researcher | Data Scientist"
baseurl: ""
url: "https://hanqiwang24.github.io"

theme: minima
